/**
 * Heritage craft categories across the Global South (South & Southeast Asia,
 * Africa, the Middle East, Latin America & the Caribbean, and the Pacific).
 * Alphabetically sorted for the onboarding select.
 */
export const CRAFT_OPTIONS = [
  "Abaca & Fiber Weaving",
  "Adinkra Textile Stamping",
  "Ajrakh Block Printing",
  "Andean Textile Weaving",
  "Aso-Ökè Weaving",
  "Banarasi Silk Weaving",
  "Batik Textiles",
  "Bhutanese Thangka Painting",
  "Bidriware Metal Inlay",
  "Blue Pottery",
  "Bogolan Mud Cloth",
  "Brass & Copper Ware",
  "Cambodian Silk Weaving",
  "Capiz Shell Craft",
  "Chikankari Embroidery",
  "Colombian Vueltiao Weaving",
  "Dhokra Metal Casting",
  "Egyptian Khayamiya Appliqué",
  "Ethiopian Leatherwork",
  "Guatemalan Backstrap Weaving",
  "Huipil & Mayan Textile Art",
  "Ikat Weaving",
  "Jamaican Straw Plaiting",
  "Kalaga Embroidery",
  "Kalamkari Painting",
  "Kani Shawl Weaving",
  "Kashmiri Copper Engraving",
  "Kente Cloth Weaving",
  "Lacquerware",
  "Leather Tooling & Saddlery",
  "Madhubani Painting",
  "Maasai Beadwork",
  "Meenakari Enamel Work",
  "Mexican Talavera Pottery",
  "Moroccan Zellige Tilework",
  "Mola Appliqué Textiles",
  "Mud & Terracotta Pottery",
  "Nariño Pottery",
  "Ndebele Mural Painting",
  "Oaxacan Alebrije Carving",
  "Palestinian Tatreez Embroidery",
  "Palm & Cane Basketry",
  "Papier Mâché",
  "Pashmina Weaving",
  "Pattachitra Painting",
  "Peranakan Beadwork",
  "Persian Carpet Weaving",
  "Peruvian Retablo Folk Art",
  "Phulkari Embroidery",
  "Piña Fiber Weaving",
  "Rattan & Wicker Weaving",
  "Roghan Painting",
  "Shona Stone Sculpture",
  "Silver Filigree Jewelry",
  "Songket Brocade Weaving",
  "Tapa Bark Cloth",
  "Thai Celadon Ceramics",
  "Tuareg Silver Jewelry",
  "Vietnamese Lacquer Painting",
  "Warli Folk Painting",
  "Wayuu Mochila Weaving",
  "Wood Carving",
  "Zardozi Embroidery",
  "Zulu Beadwork & Pottery",
] as const;

/** Live count for on-screen “is this the latest build?” checks. */
export const CRAFT_CATALOG_COUNT = CRAFT_OPTIONS.length;

export type CraftOption = (typeof CRAFT_OPTIONS)[number];
